### ISSUE TITLE
drawRandomSample: 'sample size is greater than subpopulation size'

### ISSUE THREAD

**Issue by ChrystelleDelord** [BoPeng/simuPOP-examples#3]
Hello again SimuPOP users!

This time I would like to use the drawRandomSample to export genepop files from my simulated population. I have 16 subpopulations with the same number of individuals (50 individuals per pop). I am using a heteroMating scheme in order to mimic overlapping generations, but after each mating phase I set subPopSize back to the basic fixed deme size of 50 (I did that just so it would be simpler to make some scalability tests without a demo function - maybe it is definitely wrong?). At the end of the run, I am trying to sample a few individuals (20) to export them as a genepop file.

However, I get this error message : 
`Warning: sample size (20) at subpopulation 0 is greater than subpopulation size 0.` which is odd because PyEval and PyOutput do print my 16 subpops with 50 individuals each, as expected. I guess I am missing the obvious :-). Did I omit to access to genotype information somehow?

My code is in the attached file. Thank you very much for your help!

Cheers,

Chrystelle
[Test_run.txt](https://github.com/BoPeng/simuPOP-examples/files/1480404/Test_run.txt)

**Comment by BoPeng** [comment]
From my quick glance at your code, you failed to get evolved population from the simulator. A `Simulator` is used to simulate multiple replicates of a `Population`. It clones the population and evolve separately so `pop` is not changed at all in the case of 

```
pop = ...
simu = Simulator(pop)
simu.evolve()
```
You would need to evolve `pop` directly
```
pop = ...
pop.evolve()
```
or use
```
pop = simu.extract(0)
```
at the end of the evolution to get the evolved population from the simulator.

**Comment by ChrystelleDelord** [comment]
Thank you very much Bo, I had indeed missed this subtility about replicates management.

Unfortunately I now have problems to export my sub-samples in Genepop format: call of the following commands:

`sim.utils.Exporter(format='GENEPOP', title="SimuPOP output", adjust=1, output="output.txt").apply(sample)`
`sim.utils.export(sample, format='GENEPOP', output="output.txt")`

systematically fail no matter how I rearrange the syntax. The generated output file has the right name and contains the expected 'SimuPOP output' header, with each loci name, but not the genotyped neither the 'pop_name' information field that I previously tried to declare in my code.

Thank you so much once again!

Chrystelle

**Comment by BoPeng** [comment]
Did you try to `dump` the population and see if all the information is there?

**Comment by ChrystelleDelord** [comment]
Good morning Bo, 

Thank you for your answer, I tried this indeed. The following commands
`sample = drawRandomSample(pop, sizes=[20]*16)`
`sim.dump(sample)` 

give me all the information I need (I am only interested in getting individual genotypes). But I feel like two problems are happening:
- I cannot set a new 'infoFields' to my 'sample'. 
`sample.setInfoFields('pop_name')`
`sample.infoFields() # does not return anything`
`vecname=[] # init of the population status of each individual`
`for i in range(1,numpop+1): # numpop being defined before as the length of vector 'subPopSizes' of my 'sample'.
       vecname=vecname+[i]*20`
`print(vecname) # returns the expected vector of 20*[1] + 20*[2] + ..., etc.`
`sample.setIndInfo(vecname, 'pop_name')`
`print(sample.subPopSizes()) # returns the expected 20L per subPop.`
{ print(sample.pop_name()) # returns that the 'Population' object has no defined 'pop_name'.`

- I might have, maybe, an issue with one of SimuPOP/python library?
I have attached a screen capture of what is going on when I try to export my 'sample' individuals in Genepop format, even after having removed anything associated to population status (i.e., exporting just the whole 20*16 individual without trying to set any population information to them
![screen_simupop](https://user-images.githubusercontent.com/31771617/33013152-48a0b47c-cde3-11e7-8e32-25bb88983411.PNG)
.)

Sorry about all of this inconvenience! Thank you very much in advance,


Chrys

**Comment by BoPeng** [comment]
Not sure about the 1st one but the 2nd one was caused by missing module tk. You can use `gui='batch'` to disable progress bar, or `gui=None` to use text-based progress bar.

It would be great if you could send me a working script that demonstrate the problem (after fixing the `Simulator` problem in your original script).

**Comment by ChrystelleDelord** [comment]
Thank you very much!

Setting the 'gui' argument to 'False' in my Exporter command seemed to partly resolve the issue! Unfortunately there are a few features left that I do not understand; notably what is wrong with the 'pop_name' setting for my Sample, and the fact that my k/N/m loop seems to broke after a single thread.

Also I now have a message error stating that migration rate for one of my subPop should <= 1 (I cannot see how it is not the case). New script enclosed here.
[TestMb.txt](https://github.com/BoPeng/simuPOP-examples/files/1488795/TestMb.txt)

Have a very nice evening!

**Comment by BoPeng** [comment]
Let us fix the problems one by one. After get your script running, I got error:

```
<generator object <genexpr> at 0x10ead60a0>
Traceback (most recent call last):
  File "TestMb.py", line 116, in <module>
    gen=201
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/simuPOP/__init__.py", line 406, in evolve_pop
    gen = simu.evolve(initOps, preOps, matingScheme, postOps, finalOps, gen)
ValueError: Sum of migrate rate from one subPop should <= 1
```

I then notice that the sum of the rows of your migration matrix is 20, which is wrong as the sum should be 1 (while the M_ii can be automatically calculated) with your migration mode of `BY_PROPORTION`.

Then, after I add

```
            print(sample.infoFields())
```
after `setInfo`, I got

```
('pop_name',)
```
which looks ok to me, and I can get

```
            print(sample.indInfo('pop_name'))
```
after setting the field.

So simuPOP appears to be working all right.

**Comment by ChrystelleDelord** [comment]
Awesome! I have missed this feature of the Migrator module. I will have a closer look at it. For now, lowering the highest value from 0.5 to 0.1 did enable the loop to perform well so this was indeed a problem with my migration rates (this was not very smart of me to use the "by_proportion" with such values!)

Thank you so much Bo, I wish you a very nice week :-)
